create sequence if not exists hibernate_sequence start with 1 increment by 1;
create table categoria (id_categoria integer not null, descricao varchar(45), sigla varchar(5), primary key (id_categoria));
create table cliente (id_cliente integer not null, pontuacao integer, id_pessoa integer, primary key (id_cliente));
create table contrato_locacao (id_contrato integer not null, ativo boolean, data_devolucao timestamp, data_retirada timestamp, valor_diaria double, valor_seguro double, id_cliente integer, id_filial_devolucao integer, id_filial_retirada integer, id_veiculo integer, primary key (id_contrato));
create table endereco (id_endereco integer not null, bairro_setor varchar(45), cep varchar(8) not null, lote varchar(10), numero integer, quadra varchar(10), rua varchar(45), primary key (id_endereco));
create table filial (id_filial integer not null, id_endereco integer, id_garagem integer, primary key (id_filial));
create table garagem (id_garagem integer not null, primary key (id_garagem));
create table marca (id_marca integer not null, nome varchar(45), primary key (id_marca));
create table modelo (id_modelo integer not null, nome varchar(45), primary key (id_modelo));
create table pessoa (id_pessoa integer not null, cpf varchar(11), nome varchar(45), id_endereco integer, primary key (id_pessoa));
create table veiculo (id_veiculo integer not null, placa varchar(255), id_categoria integer, id_garagem integer not null, id_modelo integer, primary key (id_veiculo));
alter table veiculo add constraint UK_s9nl6tnr8ai86bbcg13xugmua unique (id_garagem);
alter table cliente add constraint FKbjwqfll0hhesxqhyjaombdnj1 foreign key (id_pessoa) references pessoa;
alter table contrato_locacao add constraint FK76vvk90slaclrthcahltrcg7 foreign key (id_cliente) references cliente;
alter table contrato_locacao add constraint FKcsgdwhn9tq63fgjemn2hxa9je foreign key (id_filial_devolucao) references filial;
alter table contrato_locacao add constraint FKr3l5lm557nn6078l5o6unt3jo foreign key (id_filial_retirada) references filial;
alter table contrato_locacao add constraint FK8qi1vip65mauvfe91yq97c7li foreign key (id_veiculo) references veiculo;
alter table filial add constraint FKnh8i9fijlmxjol5nla6l273wr foreign key (id_endereco) references endereco;
alter table filial add constraint FK4flsucb2d5qb8gqliiqweinpk foreign key (id_garagem) references garagem;
alter table pessoa add constraint FKo2v72927b43j7ug0s8b97ymly foreign key (id_endereco) references endereco;
alter table veiculo add constraint FKsjr07rwxrd9rsjabp71fmh02b foreign key (id_categoria) references categoria;
alter table veiculo add constraint FKlmbuu61ixak5m8vrungl9qee4 foreign key (id_garagem) references garagem;
alter table veiculo add constraint FK7nb3xkqesdtf9gn9s5cmlan8j foreign key (id_modelo) references modelo;
